language: objective-c
os: osx
osx_image: xcode11.2

cache:
  directories:
    - Carthage
    - $HOME/Library/Caches/Homebrew

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - brew update
  - gem uninstall fastlane --force
  - gem install fastlane
  - which fastlane || true
  - if brew list | grep -q carthage; then
      echo Carthage installed. Proceed without installing;
      carthage version;
    else
      echo Carthage not installed. Installing using homebrew;
      brew install carthage;
    fi
  - brew upgrade swiftlint || true

jobs:
  include:
    - stage: Caches bootstrap
      script: travis_wait 600 carthage bootstrap --platform iOS --cache-builds
    - stage: run tests
      script: fastlane unitTests
      name: "Unit Tests"
    - script: fastlane integrationTests || true
      name: "Integration Tests (doesn't fail  the build)"
