language: objective-c
os: osx
osx_image: xcode11.2

cache:
  directories:
    - Carthage
    - $HOME/Library/Caches/Homebrew

install:
  - brew update
  - gem uninstall fastlane --force
  - gem install fastlane
  - which fastlane || true
  - if brew list | grep -q carthage; then
      echo Carthage installed. Proceed without installing;
      carthage version;
    else
      echo Carthage not installed. Installing using homebrew;
      brew install carthage;
    fi
  - brew upgrade swiftlint || true
  - travis_wait 600 carthage bootstrap --platform iOS --cache-builds

jobs:
  include:
    - stage: prepare caches
      script: travis_wait 600 carthage update --platform iOS --cache-builds BitcoinKit
      script: stravis_wait 600 carthage update --platform iOS --cache-builds Alamofire
      script: travis_wait 600 carthage update --platform iOS --cache-builds Entwine
      script: travis_wait 600 carthage update --platform iOS --cache-builds RxSwift
      script: travis_wait 600 carthage update --platform iOS --cache-builds RxOptional,RxSwiftExt,SwiftyBeaver
      script: travis_wait 600 carthage update --platform iOS --cache-builds BigInt,Starscream,CryptoSwift,SwiftCBOR
    - stage: run unit tests
      script:
        - fastlane unitTests
